ALTER TABLE public.estabelecimento
  ADD COLUMN IF NOT EXISTS whatsapp TEXT,
  ADD COLUMN IF NOT EXISTS endereco TEXT,
  ADD COLUMN IF NOT EXISTS cor_primaria TEXT DEFAULT '#1FB8DB',
  ADD COLUMN IF NOT EXISTS cor_secundaria TEXT DEFAULT '#0EA5E9',
  ADD COLUMN IF NOT EXISTS horario TEXT,
  ADD COLUMN IF NOT EXISTS onboarding_concluido BOOLEAN DEFAULT false;